#!/usr/bin/env bash
# =============================================================================
# Power X SMS — one-shot 24/7 production setup
# =============================================================================
#   cd /root/PowerX-SMS && bash scripts/install-service.sh
#
# Idempotent: safe to run again. It never deletes data.sqlite and never
# overwrites an existing .env.
#
# What it sets up:
#   1. .env with a strong random JWT_SECRET + disk-safe backup schedule
#   2. PM2 in fork mode with a tuned restart policy
#   3. PM2 systemd unit so the panel comes back after a reboot
#   4. pm2-logrotate so logs cannot fill the disk
#   5. systemd timer: health watchdog every 2 minutes (catches hangs)
#   6. systemd timer: disk guard every hour (catches backup bloat)
#   7. UFW firewall (SSH + panel port only)
#   8. Kernel/network tuning for a long-running Node server
# =============================================================================
set -euo pipefail

APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PM2_NAME="${PM2_NAME:-powerx}"
PORT="${PORT:-4000}"
LOG_DIR="/root/powerx-logs"
BACKUP_DIR="/root/powerx-sms-backups"

grn() { printf '\033[32m%s\033[0m\n' "$*"; }
ylw() { printf '\033[33m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*"; }
hdr() { echo; printf '\033[1m=== %s\033[0m\n' "$*"; }

[ "$(id -u)" -eq 0 ] || { red "Please run as root."; exit 1; }
cd "$APP_DIR"

hdr "1/9  Checking Node version"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
if [ "$NODE_MAJOR" -lt 20 ]; then
  red "Node 20+ required, found: $(node -v 2>/dev/null || echo none)"
  echo "  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt install -y nodejs"
  exit 1
fi
grn "  node $(node -v)  npm $(npm -v)"

hdr "2/9  Directories"
mkdir -p "$LOG_DIR" "$BACKUP_DIR"
grn "  $LOG_DIR"
grn "  $BACKUP_DIR"

hdr "3/9  .env"
if [ -f .env ]; then
  ylw "  .env already exists — leaving it untouched"
  if grep -q 'change-this-to-a-long-random-secret' .env; then
    red "  WARNING: JWT_SECRET is still the placeholder. Fix it with:"
    echo "    sed -i \"s|^JWT_SECRET=.*|JWT_SECRET=\$(openssl rand -hex 32)|\" .env"
  fi
else
  SECRET="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Power X SMS — production configuration
# Generated by scripts/install-service.sh on $(date '+%F %T')

NODE_ENV=production
PORT=$PORT

# Signing key for login tokens. Never share this; changing it logs everyone out.
JWT_SECRET=$SECRET

# Database. Kept inside the app folder; .gitignore already excludes it,
# so 'git pull' can never overwrite it.
DB_FILE=$APP_DIR/backend/data.sqlite

# ---------------------------------------------------------------------------
# Backups
# Each backup is a FULL copy of the database (backend/backup.js exportBuffer),
# not an incremental diff. The stock 3h/30d schedule keeps 240 full copies,
# which on a 400 MB database is ~94 GB and would fill this 96 GB disk.
# 6h/14d keeps 56 copies (~22 GB at 400 MB) — still plenty of restore points.
# ---------------------------------------------------------------------------
BACKUP_ENABLED=true
BACKUP_DIR=$BACKUP_DIR
BACKUP_INTERVAL_HOURS=6
BACKUP_RETENTION_DAYS=14

# Provider sync scheduler (Management -> System Master -> API Providers)
SYNC_ENABLED=true
SYNC_INTERVAL_SECONDS=12
EOF
  chmod 600 .env
  grn "  created .env with a fresh 64-char JWT_SECRET (chmod 600)"
  grn "  backups: every 6h, keep 14 days (disk-safe)"
fi

hdr "4/9  Dependencies"
npm install --omit=dev --no-audit --no-fund
grn "  ok"

hdr "5/9  PM2"
command -v pm2 >/dev/null 2>&1 || npm i -g pm2
chmod +x scripts/*.sh 2>/dev/null || true
pm2 delete "$PM2_NAME" >/dev/null 2>&1 || true
pm2 start ecosystem.config.js
pm2 save
grn "  '$PM2_NAME' started in fork mode"

hdr "6/9  Start on boot (systemd)"
pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true
systemctl enable pm2-root >/dev/null 2>&1 || true
pm2 save >/dev/null 2>&1
if systemctl is-enabled pm2-root >/dev/null 2>&1; then
  grn "  pm2-root enabled — panel restarts automatically after reboot"
else
  ylw "  could not confirm pm2-root; run manually: pm2 startup systemd -u root --hp /root"
fi

hdr "7/9  Log rotation"
pm2 install pm2-logrotate >/dev/null 2>&1 || true
pm2 set pm2-logrotate:max_size 20M        >/dev/null 2>&1 || true
pm2 set pm2-logrotate:retain 14           >/dev/null 2>&1 || true
pm2 set pm2-logrotate:compress true       >/dev/null 2>&1 || true
pm2 set pm2-logrotate:rotateInterval '0 0 * * *' >/dev/null 2>&1 || true
grn "  rotate at 20 MB or daily, keep 14 compressed"

hdr "8/9  Watchdog + disk guard timers"
# --- health watchdog -------------------------------------------------------
# PM2 restarts a process that DIES, but not one that is alive-but-frozen.
# Verified on this app: kill -STOP made /api/health time out while PM2 still
# reported "online". This timer closes that gap.
cat > /etc/systemd/system/powerx-watchdog.service <<EOF
[Unit]
Description=Power X SMS health watchdog
After=network.target

[Service]
Type=oneshot
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=PX_HEALTH_URL=http://127.0.0.1:$PORT/api/health
Environment=PX_PM2_NAME=$PM2_NAME
ExecStart=$APP_DIR/scripts/powerx-watchdog.sh
EOF

cat > /etc/systemd/system/powerx-watchdog.timer <<EOF
[Unit]
Description=Run Power X SMS health watchdog every 2 minutes

[Timer]
OnBootSec=3min
OnUnitActiveSec=2min
AccuracySec=15s
Unit=powerx-watchdog.service

[Install]
WantedBy=timers.target
EOF

# --- disk guard ------------------------------------------------------------
cat > /etc/systemd/system/powerx-diskguard.service <<EOF
[Unit]
Description=Power X SMS disk guard
After=network.target

[Service]
Type=oneshot
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=BACKUP_DIR=$BACKUP_DIR
Environment=PX_DB_FILE=$APP_DIR/backend/data.sqlite
ExecStart=$APP_DIR/scripts/powerx-diskguard.sh
EOF

cat > /etc/systemd/system/powerx-diskguard.timer <<EOF
[Unit]
Description=Run Power X SMS disk guard hourly

[Timer]
OnBootSec=10min
OnUnitActiveSec=1h
AccuracySec=5min
Unit=powerx-diskguard.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now powerx-watchdog.timer  >/dev/null 2>&1
systemctl enable --now powerx-diskguard.timer >/dev/null 2>&1
grn "  watchdog: every 2 min (restarts a frozen panel)"
grn "  diskguard: hourly (trims backups before the disk fills)"

hdr "9/9  Firewall + kernel tuning"
if command -v ufw >/dev/null 2>&1; then
  ufw allow 22/tcp     >/dev/null 2>&1 || true
  ufw allow "$PORT"/tcp >/dev/null 2>&1 || true
  yes | ufw enable     >/dev/null 2>&1 || true
  grn "  ufw: 22 + $PORT open"
else
  ylw "  ufw not installed — skipped (apt install -y ufw)"
fi

# A long-running Node server with many keep-alive connections can exhaust the
# default file-descriptor limit and the small default connection backlog.
cat > /etc/sysctl.d/99-powerx.conf <<'EOF'
# Power X SMS tuning
fs.file-max = 200000
net.core.somaxconn = 1024
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_fin_timeout = 20
net.ipv4.tcp_tw_reuse = 1
vm.swappiness = 10
EOF
sysctl -p /etc/sysctl.d/99-powerx.conf >/dev/null 2>&1 || true

grep -q 'powerx nofile' /etc/security/limits.conf 2>/dev/null || cat >> /etc/security/limits.conf <<'EOF'
# powerx nofile
root soft nofile 65535
root hard nofile 65535
EOF
mkdir -p /etc/systemd/system/pm2-root.service.d
cat > /etc/systemd/system/pm2-root.service.d/limits.conf <<'EOF'
[Service]
LimitNOFILE=65535
EOF
systemctl daemon-reload
grn "  file descriptors raised to 65535, swappiness 10"

echo
sleep 4
hdr "Result"
pm2 list
echo
echo -n "Health: "; curl -s "http://127.0.0.1:$PORT/api/health" || echo "NO RESPONSE"
echo
echo
grn "Panel:  http://$(curl -s -m 4 ifconfig.me 2>/dev/null || echo YOUR_IP):$PORT/panel-login"
echo
echo "Timers:"
systemctl list-timers 'powerx-*' --no-pager 2>/dev/null | head -4
echo
ylw "Log in with the seeded admin, then CHANGE ITS PASSWORD from the panel."
